name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Fetch curated images
        run: npm run setup:images

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc --noEmit -p tsconfig.json

      - name: Build
        run: npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist